CREATE TABLE Roles(
	ID_Rol INT AUTO_INCREMENT PRIMARY KEY,
	Nombre TEXT NOT NULL
);

CREATE TABLE Usuarios(
	ID_User INT AUTO_INCREMENT PRIMARY KEY,
	User VARCHAR(50) NOT NULL,
	Password VARCHAR(42) NOT NULL,
	Rol INT NOT NULL,
	FOREIGN KEY (Rol) REFERENCES Roles(ID_Rol) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Empleados(
	ID_Empleado INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(60) NOT NULL,
	RFC VARCHAR(13) NOT NULL,
	Telefono VARCHAR(10) NOT NULL,
	Direccion TEXT NOT NULL
);

CREATE TABLE Clientes(
	ID_Cliente INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(60) NOT NULL,
	Telefono VARCHAR(10) NOT NULL
);

CREATE TABLE Productos(
	ID_Producto INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Precio FLOAT NOT NULL,
	Disponible INT NOT NULL,
	Minimo INT NOT NULL,
	Maximo INT NOT NULL
);

CREATE TABLE Movimientos(
	ID_Movimiento INT AUTO_INCREMENT PRIMARY KEY,
	Razon VARCHAR(50) NOT NULL,
	ID_Producto INT NOT NULL,
	Cantidad INT NOT NULL,
	Fecha DATE NOT NULL,
	FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Pedidos(
	ID_Pedido INT AUTO_INCREMENT PRIMARY KEY,
	ID_Cliente INT NOT NULL,
	ID_Empleado INT NOT NULL,
	Fecha DATE NOT NULL DEFAULT NOW(),
	Hora TIME NOT NULL DEFAULT NOW(),
	Total FLOAT NOT NULL,
	FOREIGN KEY (ID_Cliente) REFERENCES Clientes(ID_Cliente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_Empleado) REFERENCES Empleados(ID_Empleado) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Detalles_Pedidos(
	ID_Pedido INT NOT NULL,
	ID_Producto INT NOT NULL,
	Cantidad INT NOT NULL,
	FOREIGN KEY (ID_Pedido) REFERENCES Pedidos(ID_Pedido) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(ID_Pedido, ID_Producto)
);
